-- Add missing profile columns to users table
ALTER TABLE users ADD COLUMN IF NOT EXISTS weight VARCHAR(255);
ALTER TABLE users ADD COLUMN IF NOT EXISTS height VARCHAR(255);
ALTER TABLE users ADD COLUMN IF NOT EXISTS gender VARCHAR(255);
ALTER TABLE users ADD COLUMN IF NOT EXISTS fitness_level VARCHAR(255);
ALTER TABLE users ADD COLUMN IF NOT EXISTS fitness_goals VARCHAR(255); 